# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: •19/20• <br>•Year Abroad•</br>
author: Jeremiah Dufourq
author_link: https://jmdufourq.com
author_description: Australian studying and working in Germany
email: contact@jmdufourq.com
description: > # this means to ignore newlines until "baseurl:"
  A travelog of my time overseas studying and working in Germany. 
  It will also include my travels to other countries and cities around Europe and North America.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://jmdufourq.com" # the base hostname & protocol for your site

# Picturefill
# A responsive image polyfill: http://scottjehl.github.io/picturefill/
picturefill: false

# Typography
# To use, publish a kit and enter the ID here. If you do not wish to use Typekit,
# leave this ID blank
typekit_kit_id: kwf5dox

# Build settings
gems: [jekyll-paginate, jekyll-emoji]
emoji:
  format: html # default html
  ascii: true # default false
  shortname: true # default true


markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed
